[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"

# Configuración para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de encabezados para recursos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración específica para el favicon
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configuración para el site.webmanifest
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400" 